apiVersion: v1
kind: Service
metadata:
  name: quantum-raspberry-tie
  labels:
    app: quantum-raspberry-tie
spec:
  selector:
    app: quantum-raspberry-tie
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
