apiVersion: v1
kind: Service
metadata:
  name: quantum-kc-demo
  namespace: quantum
  labels:
    app: quantum-kc-demo
spec:
  selector:
    app: quantum-kc-demo
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
  type: NodePort
